<?php

/**
 * @file
 * Install, update and uninstall functions for the drupaldev blog.
 */

use Drupal\Core\Field\BaseFieldDefinition;

/**
 * Implements hook_install().
 *
 * Perform actions to set up the site for this profile.
 *
 * @see system_install()
 */
function drupaldev_blog_install() {}

function drupaldev_blog_update_10001() {
  $field = BaseFieldDefinition::create('entity_reference')
    ->setLabel(t('Category'))
    ->setDescription(t('Category of the blog entry'))
    ->setRequired(FALSE)
    ->setSetting('target_type', 'taxonomy_term')
    ->setSetting('handler', 'default')
    ->setSetting('handler_settings',
            ['target_bundles' => ['blog_category_taxonomy' => 'blog_category_taxonomy']])
    ->setDisplayOptions('form', [
      'type' => 'entity_reference_autocomplete',
      'weight' => -1,
      'settings' => [
        'match_operator' => 'CONTAINS',
        'size' => '60',
        'placeholder' => '',
      ],
    ])
    ->setDisplayConfigurable('form', TRUE)
    ->setDisplayConfigurable('view', TRUE);
  \Drupal::entityDefinitionUpdateManager()
    ->installFieldStorageDefinition('blog_category', 'drupaldev_blog', 'drupaldev_blog', $field);
}