<?php

use Drupal\commerce_product\Entity\Product;
use Drupal\Core\Field\BaseFieldDefinition;

function drupaldev_commerce_update_9001() {
  $storage_definition = BaseFieldDefinition::create('string_long')
    ->setLabel(t('Shipping description'))
    ->setDescription(t('Add description to the shipping method.'))
    ->setRevisionable(TRUE)
    ->setTranslatable(TRUE)
    ->setDefaultValue('')
    ->setDisplayOptions('form', [
      'type' => 'string_textarea',
      'weight' => 25,
      'settings' => [
        'rows' => 4,
      ],
    ]);

  \Drupal::entityDefinitionUpdateManager()
    ->installFieldStorageDefinition('shipping_description', 'commerce_shipping_method', 'commerce_shipping_method', $storage_definition);
}

/**
 * Implements hook_update_N().
 */
function drupaldev_commerce_update_9002() {
  $definition = BaseFieldDefinition::create('boolean')
    ->setLabel(t('Free shipping can be applied'))
    ->setDescription(t('If free shipping can be applied for this shipping method, turn this checkbox on.'))
    ->setDefaultValue(FALSE)
    ->setDisplayOptions('form', [
      'type' => 'boolean_checkbox',
      'settings' => [
        'display_label' => TRUE,
      ],
    ])
    ->setDisplayConfigurable('view', TRUE)
    ->setDisplayConfigurable('form', TRUE);

  $definition_update_manager = \Drupal::entityDefinitionUpdateManager();
  $definition_update_manager->installFieldStorageDefinition('free_shipping_method_offer', 'commerce_shipping_method', 'commerce_shipping_method', $definition);
}

/**
 * Implements hook_update_N().
 */
function drupaldev_commerce_update_9003() {
  $english_store_id = 2;
  $german_store_id = 3;
  $query = \Drupal::entityQuery('commerce_product');
  $query->condition('stores', $english_store_id, 'IN');
  $query->accessCheck(FALSE);
  $product_ids = $query->execute();

  foreach ($product_ids as $product_id) {
    $product = Product::load($product_id);
    $existing_store_ids = $product->getStoreIds();
    $existing_store_ids[] = $german_store_id;
    $unique_store_ids = array_unique($existing_store_ids);
    $product->setStoreIds($unique_store_ids);
    $product->save();
  }
}
