<?php

/**
 * @file
 * Provides shipping same as billing functionality.
 */

use Drupal\commerce_order\Entity\Order;
use Drupal\commerce_payment\Entity\PaymentGateway;
use Drupal\commerce_product\Entity\ProductVariation;
use Drupal\commerce_promotion\Entity\Promotion;
use Drupal\Component\Datetime\Time;
use Drupal\Core\Entity\EntityInterface;
use Drupal\drupaldev_commerce\Plugin\Commerce\CheckoutPane\BillingInformation;
use Drupal\drupaldev_commerce\Plugin\Commerce\CheckoutPane\PaymentInformation;
use Drupal\drupaldev_commerce\Plugin\Commerce\CheckoutPane\PaymentMethod;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_commerce_inline_form_PLUGIN_ID_alter().
 */
function drupaldev_commerce_commerce_inline_form_customer_profile_alter(array &$inline_form, FormStateInterface $form_state, array &$complete_form) {
  // Attach the "shipping same as billing" element.
  $profile_field_copy = \Drupal::service('drupaldev_commerce.profile_field_copy');
  if ($profile_field_copy->supportsForm($inline_form, $form_state)) {
    $profile_field_copy->alterForm($inline_form, $form_state);
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function drupaldev_commerce_module_implements_alter(array &$implementations, string $hook) {
  // Disable hook commerce_shipping_commerce_inline_form_customer_profile_alter().
  // This hook adds the "My billing information is the same as my shipping
  // information" checkbox to the payment information pane.
  if ($hook === 'drupaldev_commerce_commerce_inline_form_customer_profile_alter' && isset($implementations['commerce_shipping'])) {
    unset($implementations['commerce_shipping']);
  }

  if ($hook == 'entity_presave') {
    // Move my_module_form_alter() to the end of the list.
    // \Drupal::moduleHandler()->getImplementations()
    // iterates through $implementations with a foreach loop which PHP iterates
    // in the order that the items were added, so to move an item to the end of
    // the array, we remove it and then add it.
    $group = $implementations['drupaldev_commerce'];
    unset($implementations['drupaldev_commerce']);
    $implementations['drupaldev_commerce'] = $group;
  }
}

/**
 * Implements hook_commerce_checkout_pane_info_alter().
 *
 * TODO: Remove this hook and the overridden checkout panes once
 * https://drupal.org/project/commerce/issues/3183140 is committed.
 */
function drupaldev_commerce_commerce_checkout_pane_info_alter(&$definitions) {
  if (isset($definitions['billing_information'])) {
    $definitions['billing_information']['class'] = BillingInformation::class;
  }

  if (isset($definitions['payment_information'])) {
    $definitions['payment_information']['class'] = PaymentInformation::class;
  }

  if (isset($definitions['payment_method'])) {
    $definitions['payment_method']['class'] = PaymentMethod::class;
  }
}

/**
 * Implements hook_form_alter().
 */
function drupaldev_commerce_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_id == 'commerce_checkout_flow_custom_checkout_flow' && !empty($form['#step_id']) && $form['#step_id'] == 'login') {
    googlelogin_login_button_code($form);
  }

  // Handle workflow buttons manually.
  if (strpos($form_id, 'state_machine_transition_form_commerce_order_state') !== FALSE) {
    $form_id_prefix = 'state_machine_transition_form_commerce_order_state_';
    $order_id = str_replace($form_id_prefix, '', $form_id);
    $order = Order::load($order_id);
    $payment_gateway = $order->get('payment_gateway')->first()->getValue();

    // In store payment.
    if ($payment_gateway['target_id'] == 'in_store_payment') {
      $form['actions']['awaiting_shipment']['#access'] = FALSE;
    }

    if ($payment_gateway['target_id'] != 'in_store_payment') {
      $form['actions']['available_to_pickup']['#access'] = FALSE;
    }
  }
}

/**
 * Implements hook_entity_presave().
 */
function drupaldev_commerce_entity_presave(EntityInterface $entity) {
  if ($entity instanceof Order && ($entity->getState()
        ->getId() == 'awaiting_payment' && $entity->original->getState()
        ->getId() != 'awaiting_payment')) {
    if (!$entity->payment_gateway->entity) {
      return;
    }

    $payment_gateway = $entity->payment_gateway->entity;
    if ($payment_gateway instanceof PaymentGateway) {
      switch ($payment_gateway->id()) {
        case 'in_store_payment':
        case 'cash_on_delivery':
          $order_transition = 'awaiting_payment_to_processing';
          break;
      }
    }

    if (!empty($order_transition)) {
      $order_state = $entity->getState();
      // Check if transition is allowed.
      if ($order_state->isTransitionAllowed($order_transition)) {
        $order_state->applyTransitionById($order_transition);
      }
    }
  }

  // Promotion handling.
  if ($entity instanceof ProductVariation) {
    // Delete promotion when no amount is set.
    if (
      empty($entity->get('field_discount_type')->getString()) ||
      empty($entity->get('field_discount_amount')->getString()) ||
      !empty($entity->get('field_promotion_id')->entity)
    ) {
      if (empty($entity->get('field_discount_amount')
          ->getString()) && !empty($entity->get('field_promotion_id')->entity)) {
        $entity->get('field_promotion_id')->entity->delete();
      }
      return;
    }

    if (!empty($entity->get('field_valid_from'))) {
      $valid_from = $entity->get('field_valid_from')->getValue();
      $valid_from = reset($valid_from);
      $valid_from = $valid_from['value'];
    }

    $promotion = Promotion::create([
      'name' => sprintf('Promotion: (id: %s) %s', $entity->id(), $entity->get('title')
        ->getString()),
      'order_types' => ['default'],
      'stores' => [],
      'offer' => [
        'target_plugin_id' => $entity->get('field_discount_type')->getString(),
        'target_plugin_configuration' => [
          'display_inclusive' => TRUE,
          'conditions' => [
            [
              'plugin' => 'order_item_purchased_entity:commerce_product_variation',
              'configuration' => [
                'entities' => [
                  $entity->uuid(),
                ],
              ],
            ],
          ],
          'amount' => [
            'number' => $entity->get('field_discount_amount')->getString(),
            'currency_code' => 'HUF',
          ],
        ],
      ],
      'start_date' => $valid_from,
      'status' => TRUE,
    ]);

    $promotion->save();

    $entity->set('field_promotion_id', $promotion->id());
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function drupaldev_commerce_entity_predelete(EntityInterface $entity) {
  // Delete promotion/discount from product when promotion is deleted.
  if ($entity instanceof Promotion) {
    $result = \Drupal::entityQuery('commerce_product_variation')
      ->condition('field_promotion_id.entity:commerce_promotion.promotion_id', $entity->id())
      ->execute();
    $product_variation = ProductVariation::load(reset($result));

    if ($product_variation instanceof ProductVariation) {
      $product_variation->set('field_promotion_id', []);
      $product_variation->set('field_discount_type', NULL);
      $product_variation->set('field_discount_amount', NULL);
      $product_variation->set('field_valid_from', NULL);
      $product_variation->save();
    }
  }
}