<?php

/**
 * @file
 * Provides shipping same as billing functionality.
 */

use Drupal\commerce_order\Entity\Order;
use Drupal\commerce_payment\Entity\PaymentGateway;
use Drupal\commerce_product\Entity\ProductVariation;
use Drupal\commerce_promotion\Entity\Promotion;
use Drupal\Component\Datetime\Time;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormState;
use Drupal\drupaldev_commerce\Plugin\Commerce\CheckoutPane\BillingInformation;
use Drupal\drupaldev_commerce\Plugin\Commerce\CheckoutPane\PaymentInformation;
use Drupal\drupaldev_commerce\Plugin\Commerce\CheckoutPane\PaymentMethod;
use Drupal\Core\Form\FormStateInterface;
use Drupal\profile\Entity\Profile;

/**
 * Implements hook_commerce_inline_form_PLUGIN_ID_alter().
 */
function drupaldev_commerce_commerce_inline_form_customer_profile_alter(array &$inline_form, FormStateInterface $form_state, array &$complete_form) {
  // Attach the "shipping same as billing" element.
  $profile_field_copy = \Drupal::service('drupaldev_commerce.profile_field_copy');
  if ($profile_field_copy->supportsForm($inline_form, $form_state)) {
    $profile_field_copy->alterForm($inline_form, $form_state);
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function drupaldev_commerce_module_implements_alter(array &$implementations, string $hook) {
  // Disable hook commerce_shipping_commerce_inline_form_customer_profile_alter().
  // This hook adds the "My billing information is the same as my shipping
  // information" checkbox to the payment information pane.
  if ($hook === 'commerce_shipping_commerce_inline_form_customer_profile_alter' && isset($implementations['commerce_shipping'])) {
    unset($implementations['commerce_shipping']);
  }

  if ($hook == 'entity_presave') {
    // Move my_module_form_alter() to the end of the list.
    // \Drupal::moduleHandler()->getImplementations()
    // iterates through $implementations with a foreach loop which PHP iterates
    // in the order that the items were added, so to move an item to the end of
    // the array, we remove it and then add it.
    $group = $implementations['drupaldev_commerce'];
    unset($implementations['drupaldev_commerce']);
    $implementations['drupaldev_commerce'] = $group;
  }
}

/**
 * Implements hook_commerce_checkout_pane_info_alter().
 *
 * TODO: Remove this hook and the overridden checkout panes once
 * https://drupal.org/project/commerce/issues/3183140 is committed.
 */
function drupaldev_commerce_commerce_checkout_pane_info_alter(&$definitions) {
  if (isset($definitions['billing_information'])) {
    $definitions['billing_information']['class'] = BillingInformation::class;
  }

  if (isset($definitions['payment_information'])) {
    $definitions['payment_information']['class'] = PaymentInformation::class;
  }

  if (isset($definitions['payment_method'])) {
    $definitions['payment_method']['class'] = PaymentMethod::class;
  }
}

/**
 * Implements hook_form_alter().
 */
function drupaldev_commerce_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_id == 'commerce_checkout_flow_custom_checkout_flow' && !empty($form['#step_id']) && $form['#step_id'] == 'login') {
    googlelogin_login_button_code($form);
  }

  // Handle workflow buttons manually.
  if (strpos($form_id, 'state_machine_transition_form_commerce_order_state') !== FALSE) {
    $form_id_prefix = 'state_machine_transition_form_commerce_order_state_';
    $order_id = str_replace($form_id_prefix, '', $form_id);
    $order = Order::load($order_id);
    $payment_gateway = $order->get('payment_gateway')->first()->getValue();

    // In store payment.
    if ($payment_gateway['target_id'] == 'in_store_payment') {
      $form['actions']['awaiting_shipment']['#access'] = FALSE;
    }

    if ($payment_gateway['target_id'] != 'in_store_payment') {
      $form['actions']['available_to_pickup']['#access'] = FALSE;
    }
  }

  if ($form_id == 'commerce_checkout_flow_custom_checkout_flow' && !empty($form['#step_id']) && $form['#step_id'] == 'payment_information') {
    if (!empty($form["billing_profile"]["profile"]["address"]["widget"][0]['address'])) {
      $form["billing_profile"]["profile"]["address"]["widget"][0]['address']['#after_build'][] = 'drupaldev_commerce_customize_address';
    }
  }

  if ($form_id == 'user_register_form') {
    $form['customer_profiles']["widget"][0]['#after_build'][] = 'drupaldev_commerce_customize_address';
  }

  if ($form_id == 'profile_customer_edit_form' || $form_id == 'profile_customer_address-book-edit_form') {
    $form['address']["widget"][0]['#after_build'][] = 'drupaldev_commerce_customize_address';
    $form['actions']['submit']['#submit'][] = '_drupaldev_commerce_profile_form_submit';
    $form['tax_number']['#access'] = FALSE;
  }

  if ($form_id == 'profile_customer_address-book-add_form') {
    $form['address']["widget"][0]['#after_build'][] = 'drupaldev_commerce_customize_address';
  }
}

/**
 * Custom callback for profile form submit.
 *
 * @param array $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function _drupaldev_commerce_profile_form_submit(array &$form, FormStateInterface $form_state) {
  $values = $form_state->getValues();
  $address = $values['address'][0]['address'];

  if (!empty($address['profile_id'])) {
    $profile = Profile::load($address['profile_id']);
    $profile->setData('tax_number', $address['tax_number']);
    $profile->save();
  }
}

/**
 * Form alter callback.
 */
function drupaldev_commerce_customize_address($element, FormStateInterface $form_state) {
  $form_state_values = $form_state->getValues();
  $profile = $form_state->getformObject()->getEntity();
  $element['address']['tax_number'] = [
    '#type' => 'textfield',
    '#title' => t('Tax number'),
    '#name' => 'address[0][address][tax_number]',
    '#size' => 20,
    '#value' => !empty($form_state_values['address'][0]['address']['tax_number']) ? $form_state_values['address'][0]['address']['tax_number'] : $profile->getData('tax_number'),
    '#attributes' => [
      'class' => ['tax-number'],
      'autocomplete' => 'tax-number',
      'data-drupal-selector' => 'edit-payment-information-billing-information-address-0-address-tax-number',
      'placeholder' => 'xxxxxxxx-x-xx',
      'minlength' => 13,
      'maxlength' => 13,
      'pattern' => '[0-9]{8}-[0-9]{1}-[0-9]{2}',
      'id' => 'tax_number',
      '#pattern_error' => t('The format of the tax number is xxxxxxxx-x-xx where each x is replaced by an integer.'),
    ],
    '#states' => [
      'required' => [
        [':input[name="address[0][address][organization]"]' => ['!value' => '']],
      ],
      'visible' => [
        [':input[name="address[0][address][organization]"]' => ['!value' => '']],
      ],
    ],
    '#parents' => [
      'address',
      0,
      'address',
    ],
  ];

  $element['address']['phone_number'] = [
    '#type' => 'textfield',
    '#title' => t('Phone number'),
    '#name' => 'address[0][address][phone_number]',
    '#size' => 20,
    '#attributes' => [
      'class' => ['phone-number'],
      'autocomplete' => 'tel',
      'data-drupal-selector' => 'edit-payment-information-billing-information-address-0-address-phone-number',
      'pattern' => "^[0-9 ()\\-+/\"]*$",
      'minlength' => 10,
      'maxlength' => 20,
    ],
    '#weight' => 10,
    '#parents' => [
      'address',
      0,
      'address',
    ],
  ];

  $element['address']['profile_id'] = [
    '#type' => 'hidden',
    '#title' => t('Profile id'),
    '#name' => 'address[0][address][profile_id]',
    '#value' => $form_state->getformObject()->getEntity()->id(),
    '#parents' => [
      'address',
      0,
      'address',
    ],
  ];

  // Profile edit.
  if (!empty($element['address']['tax_number'])) {
    $weight = (!empty($element['address']['organization']['#weight'])) ? ($element['address']['organization']['#weight'] + 0.00001) : 0.001;
    $element['address']['tax_number']['#weight'] = $weight;
  }

  return $element;
}

/**
 * Implements hook_field_widget_form_alter().
 */
function drupaldev_commerce_field_widget_form_alter(&$element, &$form_state, $context) {
  if (!empty($element['address'])) {
    $element['address']['#element_validate'][] = '_drupaldev_commerce_address_tax_number_field_validate';
  }
}

/**
 * Validate vat number.
 *
 * @param array $element
 *   Element to validate.
 * @param \Drupal\Core\Form\FormState $form_state
 *   Form state.
 */
function _drupaldev_commerce_address_tax_number_field_validate(&$element, FormStateInterface $form_state) {
  $form_state_values = $form_state->getValue('address');
  $address = $form_state_values[0]['address'];

  // Set the error on the form element.
  if (!empty($address['organization']) && empty($address['tax_number'])) {
    $form_state->setErrorByName('address][0][address][tax_number', t('Tax number is empty.'));
  }

  if (!empty($address['organization']) && !empty($address['tax_number'])) {
    if (!preg_match('/[0-9]{8}-[0-9]{1}-[0-9]{2}/m', $address['tax_number'])) {
      $form_state->setErrorByName('address][0][address][tax_number', t('The format of the tax number is xxxxxxxx-x-xx where each x is replaced by an integer.'));
    }
  }
}

/**
 * Implements hook_entity_presave().
 */
function drupaldev_commerce_entity_presave(EntityInterface $entity) {
  if ($entity instanceof Order && ($entity->getState()
        ->getId() == 'awaiting_payment' && $entity->original->getState()
        ->getId() != 'awaiting_payment')) {
    if (!$entity->payment_gateway->entity) {
      return;
    }

    $payment_gateway = $entity->payment_gateway->entity;
    if ($payment_gateway instanceof PaymentGateway) {
      switch ($payment_gateway->id()) {
        case 'in_store_payment':
        case 'cash_on_delivery':
          $order_transition = 'awaiting_payment_to_processing';
          break;
      }
    }

    if (!empty($order_transition)) {
      $order_state = $entity->getState();
      // Check if transition is allowed.
      if ($order_state->isTransitionAllowed($order_transition)) {
        $order_state->applyTransitionById($order_transition);
      }
    }
  }

  // Promotion handling.
  if ($entity instanceof ProductVariation) {
    // Delete promotion when no amount is set.
    if (
      empty($entity->get('field_discount_type')->getString()) ||
      empty($entity->get('field_discount_amount')->getString()) ||
      !empty($entity->get('field_promotion_id')->entity)
    ) {
      if (empty($entity->get('field_discount_amount')
          ->getString()) && !empty($entity->get('field_promotion_id')->entity)) {
        $entity->get('field_promotion_id')->entity->delete();
      }
      return;
    }

    if (!empty($entity->get('field_valid_from'))) {
      $valid_from = $entity->get('field_valid_from')->getValue();
      $valid_from = reset($valid_from);
      $valid_from = $valid_from['value'];
    }

    $promotion = Promotion::create([
      'name' => sprintf('Promotion: (id: %s) %s', $entity->id(), $entity->get('title')
        ->getString()),
      'order_types' => ['default'],
      'stores' => [],
      'offer' => [
        'target_plugin_id' => $entity->get('field_discount_type')->getString(),
        'target_plugin_configuration' => [
          'display_inclusive' => TRUE,
          'conditions' => [
            [
              'plugin' => 'order_item_purchased_entity:commerce_product_variation',
              'configuration' => [
                'entities' => [
                  $entity->uuid(),
                ],
              ],
            ],
          ],
          'amount' => [
            'number' => $entity->get('field_discount_amount')->getString(),
            'currency_code' => 'HUF',
          ],
        ],
      ],
      'start_date' => $valid_from,
      'status' => TRUE,
    ]);

    $promotion->save();

    $entity->set('field_promotion_id', $promotion->id());
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function drupaldev_commerce_entity_predelete(EntityInterface $entity) {
  // Delete promotion/discount from product when promotion is deleted.
  if ($entity instanceof Promotion) {
    $result = \Drupal::entityQuery('commerce_product_variation')
      ->condition('field_promotion_id.entity:commerce_promotion.promotion_id', $entity->id())
      ->execute();
    $product_variation = ProductVariation::load(reset($result));

    if ($product_variation instanceof ProductVariation) {
      $product_variation->set('field_promotion_id', []);
      $product_variation->set('field_discount_type', NULL);
      $product_variation->set('field_discount_amount', NULL);
      $product_variation->set('field_valid_from', NULL);
      $product_variation->save();
    }
  }
}
