<?php

/**
 * @file
 * Provides shipping same as billing functionality.
 */

use Drupal\commerce_order\Entity\Order;
use Drupal\commerce_payment\Entity\PaymentGateway;
use Drupal\Core\Entity\EntityInterface;
use Drupal\drupaldev_commerce\Plugin\Commerce\CheckoutPane\BillingInformation;
use Drupal\drupaldev_commerce\Plugin\Commerce\CheckoutPane\PaymentInformation;
use Drupal\drupaldev_commerce\Plugin\Commerce\CheckoutPane\PaymentMethod;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_commerce_inline_form_PLUGIN_ID_alter().
 */
function drupaldev_commerce_commerce_inline_form_customer_profile_alter(array &$inline_form, FormStateInterface $form_state, array &$complete_form) {
  // Attach the "shipping same as billing" element.
  $profile_field_copy = \Drupal::service('drupaldev_commerce.profile_field_copy');
  if ($profile_field_copy->supportsForm($inline_form, $form_state)) {
    $profile_field_copy->alterForm($inline_form, $form_state);
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function drupaldev_commerce_module_implements_alter(array &$implementations, string $hook) {
  // Disable hook commerce_shipping_commerce_inline_form_customer_profile_alter().
  // This hook adds the "My billing information is the same as my shipping
  // information" checkbox to the payment information pane.
  if ($hook === 'commerce_inline_form_customer_profile_alter' && isset($implementations['commerce_shipping'])) {
    unset($implementations['commerce_shipping']);
  }
}

/**
 * Implements hook_commerce_checkout_pane_info_alter().
 *
 * TODO: Remove this hook and the overridden checkout panes once
 * https://drupal.org/project/commerce/issues/3183140 is committed.
 */
function drupaldev_commerce_commerce_checkout_pane_info_alter(&$definitions) {
  if (isset($definitions['billing_information'])) {
    $definitions['billing_information']['class'] = BillingInformation::class;
  }

  if (isset($definitions['payment_information'])) {
    $definitions['payment_information']['class'] = PaymentInformation::class;
  }

  if (isset($definitions['payment_method'])) {
    $definitions['payment_method']['class'] = PaymentMethod::class;
  }
}

/**
 * Implements hook_form_alter().
 */
function drupaldev_commerce_form_alter(&$form, FormStateInterface &$form_state, $form_id) {
  if ($form_id == 'commerce_checkout_flow_custom_checkout_flow' && !empty($form['#step_id']) && $form['#step_id'] == 'login') {
    googlelogin_login_button_code($form);
  }

  // Handle workflow buttons manually.
  if (strpos($form_id, 'state_machine_transition_form_commerce_order_state') !== FALSE) {
    // @todo handle here.
    // Home delivery
    //$form['actions']['available_to_pickup']['#access'] = FALSE;

    //dpm($form);
  }
}
