<?php

/**
 * @file
 * Provides a demo store for Commerce.
 */
/**
 * @file
 * Provides a demo store for Commerce.
 */

/**
 * Implements hook_modules_installed().
 */
function drupaldev_default_content_modules_installed($modules) {
  if (in_array('drupaldev_default_content', $modules, TRUE) && !\Drupal::isConfigSyncing()) {
    /*$index_storage = \Drupal::entityTypeManager()->getStorage('search_api_index');
    $index = $index_storage->load('products');
    $index->indexItems();*/
  }
}