<?php

/**
 * @file
 * Webshop Image Formatter
 * David Czinege - <czinege.david.89@gmail.com> - Creativenet Ltd. - Kecskemet, Hungary - 2016
 */

use Drupal\Component\Utility\Html;
use Drupal\image\Entity\ImageStyle;
use Drupal\file\Entity\File;
use Drupal\wif\Entity\WifPreset;
use Drupal\responsive_image\Entity\ResponsiveImageStyle;

/**
 * Implements hook_theme().
 */
function wif_theme() {
  return array(
    'webshop_image_formatter' => array(
      'variables' => array(
        'selected_wif_preset' => NULL,
        'items' => NULL,
      ),
    ),
  );
}
/**
 * Prepares variables for image formatter templates.
 *
 * Default template: image-formatter.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - item: An ImageItem object.
 *   - item_attributes: An optional associative array of html attributes to be
 *     placed in the img tag.
 *   - image_style: An optional image style.
 *   - url: An optional \Drupal\Core\Url object.
 */
function template_preprocess_webshop_image_formatter(&$variables) {
  if ( count($variables['items']) == 0 ) {return;}

  $variables['custom_id'] = Html::getId('webshop-image-formatter');

  if ( !empty($variables['selected_wif_preset']) ) {
    $wif_preset = wif_preset_load($variables['selected_wif_preset']);
    $variables['image_style_zoomed'] = $wif_preset->image_style_zoomed;
    $variables['image_style_normal'] = $wif_preset->image_style_normal;
    $variables['image_style_thumb'] = $wif_preset->image_style_thumb;
  }

  foreach ($variables['items'] as $delta => $item) {
    // Build images.

    if(!$item['item'] instanceof File){
      $file = File::load($item['item']->get('target_id')->getValue());
    } else {
      $file = $item['item'];
    }

    if($file instanceof File){

      // Zoomed image
      if ( $variables['image_style_zoomed'] ) {
        $style = ImageStyle::load($variables['image_style_zoomed']);
        $variables['items'][$delta]['zoomed'] = $style->buildUrl($file->getFileUri());
      } else {
        $variables['items'][$delta]['zoomed'] = file_create_url($file->getFileUri());
      }

      // Slide image
      if ( $variables['image_style_normal'] ) {
        // Responsive image handling.
        if (strpos($variables['image_style_normal'], '-responsive') !== FALSE) {
          $responsive_image_style_name = str_replace('-responsive', '', $variables['image_style_normal']);
          $variables['items'][$delta]['slide'] = wif_load_responsive_image($delta,$file, $responsive_image_style_name, ['alt' => $item['alt'], 'title' => $item['title']]);
          $variables['items'][$delta]['is_responsive'] = true;
        } else {
          $style = ImageStyle::load($variables['image_style_normal']);
          $variables['items'][$delta]['slide'] = $style->buildUrl($file->getFileUri());
        }
        $image_factory = \Drupal::service('image.factory')->get($style->buildUri($file->getFileUri()));
        $variables['items'][$delta]['height'] = $image_factory->getToolkit()->getHeight();
        $variables['items'][$delta]['width'] = $image_factory->getToolkit()->getWidth();
      } else {
        $variables['items'][$delta]['slide'] = file_create_url($file->getFileUri());
      }

      // Thumbnail image
      if ( $variables['image_style_thumb'] ) {
        if (strpos($variables['image_style_thumb'], '-responsive') !== FALSE) {
          $responsive_image_style_name = str_replace('-responsive', '', $variables['image_style_thumb']);
          $variables['items'][$delta]['thumb'] = wif_load_responsive_image($delta, $file, $responsive_image_style_name, ['alt' => $item['alt'], 'title' => $item['title']]);
          $variables['items'][$delta]['is_responsive'] = true;
        } else {
          $style = ImageStyle::load($variables['image_style_thumb']);
          $variables['items'][$delta]['thumb'] = $style->buildUrl($file->getFileUri());
        }
      } else {
        $variables['items'][$delta]['thumb'] = file_create_url($file->getFileUri());
      }

      $variables['items'][$delta]['alt'] = $item['alt'];
      $variables['items'][$delta]['title'] = $item['title'];
    }
  }
}

/**
 * Menu argument loader. Returns a wif_preset entity
 *
 * @param $id
 * @return \Drupal\Core\Entity\EntityInterface|static
 */
function wif_preset_load($id) {
  return WifPreset::load($id);
}


function wif_load_responsive_image($delta, $file, $responsive_image_style_name, $attributes = []) {
  $responsive_image_style = ResponsiveImageStyle::load($responsive_image_style_name);
  $display_options = [
    'responsive_image_style_id' => $responsive_image_style->getOriginalId(),
    'uri' => $file->getFileUri(),
  ];

  $image = \Drupal::service('image.factory')->get($file->getFileUri());

  if ($image->isValid()) {
    $display_options['width'] = $image->getWidth();
    $display_options['height'] = $image->getHeight();
  }
  else {
    $display_options['width'] = $display_options['height'] = NULL;
  }

  return [
    '#theme' => 'responsive_image',
    '#width' => $display_options['width'],
    '#height' => $display_options['height'],
    '#responsive_image_style_id' => $display_options['responsive_image_style_id'],
    '#uri' => $display_options['uri'],
    '#attributes' => $attributes,
  ];
}
