<?php

use Drupal\block\Entity\Block;
use Drupal\views\Views;


function drupaldev_theme_preprocess(&$variables) {
  $variables['base_url'] = 'http' . (isset($_SERVER['HTTPS']) ? 's' : '') . '://' . "{$_SERVER['HTTP_HOST']}";
}
function drupaldev_theme_preprocess_html(&$variables) {
  $route = \Drupal::routeMatch()->getRouteName();

  // Thin style anonymous user pages
  if (
    $route == 'user.login' ||
    $route == 'user.register' ||
    $route == 'user.pass' ||
    $route == 'entity.user.edit_form' ||
    $route == 'user.reset' ||
    $route == 'change_pwd_page.change_password_form'
  ) {
    $variables['attributes']['class'][] = 'page-style-thin';
  }
}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function drupaldev_theme_preprocess_page(&$variables) {
  $variables['container_fluid'] = FALSE;
  $variables['container_class'] = $variables['container_fluid'] ? 'container-fluid' : 'container';

  $store = \Drupal::service('commerce_store.current_store')->getStore();
  $cart = \Drupal::service('commerce_cart.cart_provider')
    ->getCart('default', $store);

  if($cart instanceof Drupal\commerce_order\Entity\Order){
    $count = 0;
    foreach ($cart->getItems() as $order_item) {
      $count += (int) $order_item->getQuantity();
    }
    $variables['in_commerce_cart'] = $count;
  } else {
    $variables['in_commerce_cart'] = 0;
  }
}

function drupaldev_theme_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {

  if($form_id == 'user_login_form'){
    unset($form['name']['#description']);
    unset($form['pass']['#description']);
    $form['actions']['#suffix'] = '<div class="google-login-separator">' . t('or') . '</div>';
  }

  if($form_id == 'user_register_form'){
    unset($form['account']['mail']['#description']);
    unset($form['account']['pass']['#description']);
  }

  if ($form['#form_id'] == 'views_exposed_form') {
    $form['search_api_fulltext']['#title_display'] = 'invisible';
    $form['actions']['submit']['#has_icon'] = TRUE;
    $form['actions']['submit']['#only_icon'] = TRUE;
    $form['actions']['submit']['#icon_type'] = 'search';
  }

  if( strpos($form_id, 'views_form_commerce_cart_form') !== false ){
    $form['#attached']['library'][] = 'drupaldev_theme/cart-data-table';

    foreach ( $form['remove_button'] as $key => $value ){
      if(is_array($value)){
        $form['remove_button'][$key]['#has_icon'] = TRUE;
        $form['remove_button'][$key]['#only_icon'] = TRUE;
        $form['remove_button'][$key]['#icon_type'] = 'delete';
      }
    }
  }
}


function drupaldev_theme_preprocess_views_view_table(&$variables) {
  if( $variables['view']->id() == 'commerce_cart_form' ){
    $variables['attributes']['id'] = 'commerce-cart-form--table';
    $variables['attributes']['class'][] = 'display';
  }
}

use Drupal\comment\CommentInterface;

/**
 * Implements hook_comment_links_alter().
 */
function drupaldev_theme_comment_links_alter(array &$links, CommentInterface $comment, array &$context) {
  $content_type = $context['commented_entity']->bundle();
  $comment_type = $comment->bundle();

  if (($content_type == 'YOUR_CONTENT_TYPE') && ($comment_type == 'YOUR_COMMENT_TYPE')) {
    unset($links['comment']['#links']['comment-reply']);;
  }
}


function drupaldev_theme_theme_suggestions_block_alter(array &$suggestions, array $variables) {

  if (!empty($variables['elements']['#id'])) {
    $block = Block::load($variables['elements']['#id']);
    $suggestions[] = 'block__' . $block->getRegion();
    if(isset($variables['elements']['#base_plugin_id'])){
      $suggestions[] = 'block__' . $block->getRegion() . '__' . $variables['elements']['#base_plugin_id'];
    }
    $suggestions[] = 'block__' . $block->getRegion() . '__' . $variables['elements']['#id'];
  }
  /* Use this 'else if' only if you are using page_manager module and want to know which region is the block */
  else {
    if (isset($variables['elements']['#configuration']['region'])) {
      $suggestions[] = 'block__page_' . $variables['elements']['#configuration']['region'];
      $suggestions[] = 'block__page_' . $variables['elements']['#configuration']['region'] . '__' . end(explode(':', $variables['elements']['#plugin_id']));
    }
  }
  return $suggestions;
}

