<?php

/**
 * @file
 * Drupaldev search module file.
 */

use Drupal\Core\Cache\Cache;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Markup;
use Drupal\drupaldev_search\Entity\DrupaldevSearchAlias;
use Drupal\taxonomy\Entity\Term;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;

/**
 * Implements hook_theme().
 */
function drupaldev_search_theme($existing, $type, $theme, $path) {
  return [
    'search_description_block' => [
      'variables' => [
        'content' => NULL,
        'long_used' => FALSE,
      ],
    ],
  ];
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Test
 */

function drupaldev_search_form_facets_facet_edit_form_alter(&$form, FormStateInterface $form_state) {
  // Load the facet and facet source configuration.
  $facet = \Drupal::routeMatch()->getParameter('facets_facet');
  $facetsource_config = $facet->getFacetSourceConfig();

  // Only alter form when pretty paths is active.
  if ($facetsource_config->getUrlProcessorName() == 'drupaldev_url_processor') {
    /* @var $pretty_paths_coder_manager \Drupal\facets_pretty_paths\Coder\CoderPluginManager */
    $pretty_paths_coder_manager = \Drupal::service('plugin.manager.drupaldev_search.coder');
    $coders = [];
    $coder_descriptions = [];
    foreach ($pretty_paths_coder_manager->getDefinitions() as $coder_id => $definition) {
      $coders[$definition['id']] = !empty($definition['label']) ? $definition['label'] : $coder_id;
      $coder_descriptions[$definition['id']] = !empty($definition['description']) ? $definition['description'] : '';
    }
    $form['facet_settings']['drupaldev_search_coder'] = [
      '#type' => 'radios',
      '#title' => t('Drupaldev Search coder'),
      '#options' => $coders,
      '#default_value' => $facet->getThirdPartySetting('drupaldev_search', 'coder', 'default_coder'),
    ];

    foreach ($coder_descriptions as $coder_id => $coder_description) {
      $form['facet_settings']['drupaldev_search_coder'][$coder_id]['#description'] = $coder_description;
    }

    // We need to add our custom submit handler before the defaults. If we
    // trigger after the defaults, $facet->save() will break the entity form.
    array_unshift($form['actions']['submit']['#submit'], "drupaldev_search_facet_edit_form_submit");
  }
}

/**
 * Custom submit handler which saves the selected coder for a given facet.
 */
function drupaldev_search_facet_edit_form_submit(&$form, FormStateInterface $form_state) {
  $coder = $form_state->getValue(['facet_settings', 'drupaldev_search_coder']);
  $facet = \Drupal::routeMatch()->getParameter('facets_facet');
  $facet->setThirdPartySetting('drupaldev_search', 'coder', $coder);
  $facet->save();
}

/**
 * Implements hook_views_post_render().
 */
function drupaldev_search_views_post_render($view) {
  if (strpos($view->storage->get('base_table'), 'search_api') !== FALSE) {
    $query = $view->getRequest()->query->all();
    $title = [];

    foreach ($query as $key => $q) {
      if ($key == 'page' || $key == 'search_api_fulltext' || $key == 'v' || $key == 'k') {
        continue;
      }

      foreach ($q as $q2) {
        $filter_value = explode(':', $q2);
        $term = Term::load($filter_value[1]);

        if ($term instanceof Term) {
          $title[] = $term->getName();
        }
        else {
          $title[] = $filter_value[1];
        }
      }
    }

    $parameters = \Drupal::routeMatch()->getRawParameters();

    $alias = implode('-', $parameters->all());

    $search_alias_query = \Drupal::entityQuery('drupaldev_search_alias');
    $search_alias_query->condition('alias', $alias);
    $search_alias_query->condition('langcode', \Drupal::languageManager()->getCurrentLanguage()->getId());
    $search_alias_query->accessCheck(FALSE);
    $results = $search_alias_query->execute();

    if (empty($results)) {
      return;
    }

    $result = reset($results);
    $search_alias = DrupaldevSearchAlias::load($result);

    if (!empty($search_alias) && $view->id() == 'products') {
      $title = $search_alias->getTitleWithFilters();

      // Set view and page titles.
      $view->setTitle($title);
      \Drupal::routeMatch()->getRouteObject()->setDefault(
        '_title',
        $title
      );
    }
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function drupaldev_search_page_attachments_alter(&$attachments) {
  $parameters = \Drupal::routeMatch()->getRawParameters();
  $route_name = \Drupal::routeMatch()->getRouteName();

  if (!in_array($route_name, ['entity.commerce_product.canonical', 'view.products.page_1']) && !str_contains($route_name, 'drupaldev.search_route')) {
    return;
  }

  $alias = implode('-', $parameters->all());

  $search_alias_query = \Drupal::entityQuery('drupaldev_search_alias');
  $search_alias_query->condition('alias', $alias);
  $search_alias_query->condition('langcode', \Drupal::languageManager()->getCurrentLanguage()->getId());
  $search_alias_query->accessCheck(FALSE);
  $results = $search_alias_query->execute();

  if (empty($results)) {
    return [];
  }

  $result = reset($results);
  $search_alias = DrupaldevSearchAlias::load($result);

  if (!$search_alias instanceof DrupaldevSearchAlias) {
    return;
  }

  foreach ($attachments['#attached']['html_head'] as $key => $attachment) {
    if (!empty($attachment[0]['#tag']) && $attachment[0]['#tag'] == 'meta' && in_array($attachment[1], [
        'og_title',
        'dcterms_title',
        'title',
        'description',
        'og_description',
        'dcterms_description',
      ])) {
      unset($attachments['#attached']['html_head'][$key]);
    }
  }

  // Add new metas.
  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'meta',
      '#attributes' => [
        'property' => 'og:title',
        'content' => $search_alias->getTitleWithFilters(),
      ],
    ],
    'og_title',
  ];
  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'meta',
      '#attributes' => [
        'name' => 'dcterms.title',
        'content' => $search_alias->getTitleWithFilters(),
      ],
    ],
    'dcterms_title',
  ];

  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'meta',
      '#attributes' => [
        'name' => 'description',
        'content' => $search_alias->getMetaDescriptionWithFilters(),
      ],
    ],
    'description',
  ];
  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'meta',
      '#attributes' => [
        'property' => 'og:description',
        'content' => $search_alias->getMetaDescriptionWithFilters(),
      ],
    ],
    'og_description',
  ];
  $attachments['#attached']['html_head'][] = [
    [
      '#tag' => 'meta',
      '#attributes' => [
        'property' => 'dcterms.description',
        'content' => $search_alias->getMetaDescriptionWithFilters(),
      ],
    ],
    'dcterms_description',
  ];
}

/**
 * Implements hook_views_data_alter().
 *
 * We need to look through and change the field handler for our stored item to
 * our custom handler so HTML is unescaped.
 *
 * @param array $data
 */
function drupaldev_search_views_data_alter(array &$data) {
  try {
    $indices = \Drupal::entityTypeManager()
      ->getStorage('search_api_index')
      ->loadMultiple();
    $views_data_keys = array_keys($data);

    if ($indices) {
      foreach (array_keys($indices) as $index) {
        $views_index_name = 'search_api_index_' . $index;

        if (!in_array($views_index_name, $views_data_keys)) {
          continue;
        }

        foreach (array_keys($data[$views_index_name]) as $item) {
          if ($item == 'search_api_rendered_item' || $item == 'rendered_item' || $item == 'related_products') {
            $data[$views_index_name][$item]['field']['id'] = 'search_api_view_mode';
            $data[$views_index_name][$item]['field']['fallback_handler'] = 'search_api_view_modes';
          }
        }
      }
    }
  }
  catch (\Exception $e) {
  }
}


/**
 * Implements hook_preprocess_page().
 *
 */
function drupaldev_search_preprocess_page(&$variables) {
  //var_dump(\Drupal::routeMatch()->getRouteName());
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function drupaldev_search_commerce_product_variation_update(\Drupal\commerce_product\Entity\ProductVariation $product_variation) {
  //We need to automatic translate the variation to all languages
  $langcodes = \Drupal::languageManager()->getLanguages();
  $langcodesList = array_keys($langcodes);
  /* @var $product \Drupal\commerce_product\Entity\Product */
  $product = $product_variation->getProduct();
  if($product_variation->isDefaultTranslation()){
    foreach ($langcodesList as $lang_code) {
      if($product_variation->language()->getId() !== $lang_code && $product_variation->isDefaultTranslation()){
        if($product->hasTranslation($lang_code)) {
          if($product_variation->hasTranslation($lang_code)){
            $product_variation_translation = $product_variation->getTranslation($lang_code);
          } else {
            $product_variation_translation = $product_variation->addTranslation($lang_code,$product_variation->toArray());
          }
          $product_variation_translation->save();
        } else {
          if($product_variation->hasTranslation($lang_code)){
            $product_variation->removeTranslation($lang_code);
            $product_variation->save();
          }
        }


      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_update().
 */
function drupaldev_search_commerce_product_update(\Drupal\commerce_product\Entity\Product $product) {
  foreach($product->getVariations() as $product_variation){
    $product_variation->save();
  }
}

/**
 * Implements hook_taxonomy_term_presave().
 */
function drupaldev_search_taxonomy_term_presave(EntityInterface $entity) {
  $tags = [];
  if ($entity->hasField('field_seo_description')) {
    $tags[] = 'seo_description:' . $entity->id();
  }

  if ($tags) {
    Cache::invalidateTags($tags);
  }
}
