<?php

/**
 * @file
 * Provides functions for the module.
 */

use Drupal\search_api\Entity\Index;
use Drupal\taxonomy\Entity\Term;

/**
 * Implements hook_theme().
 */
function taxonomy_menu_block_theme($existing, $type, $theme, $path) {
  return [
    'taxonomy_menu_block' => [
      'variables' => [
        'tree' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_presave().
 */
function taxonomy_menu_block_entity_presave($entity) {
  if ($entity instanceof Term && $entity->bundle() == 'catalog') {
    $storage = \Drupal::entityTypeManager()->getStorage('commerce_product');
    $query = $storage->getQuery();

    $query->condition('field_catalog', [(int) $entity->id()], 'IN');

    // Add the group to the query.
    $ids = $query->execute();

    if (empty($ids)) {
      return;
    }

    $products = $storage->loadMultiple($ids);

    // Reindex Product index
    $language = 'en';

    // Reindex Taxonomy index for menu
    $index = Index::load('taxonomy_index_for_menu');
    if (!$index) {
      return;
    }
    foreach ($products as $product) {
      $item_to_load = 'entity:commerce_product/' . $product->id() . ':' . $language;
      $item = $index->loadItem($item_to_load);
      if ($item) {
        $index->trackItemsUpdated('entity:commerce_product', [$product->id() . ':' . $language]);
      }
    }
  }
}
